### ISSUE TITLE
Intel bluetooth firmware not pulled into the initramfs image

### ISSUE THREAD

**Issue by oxplot** [irreleph4nt/mkinitcpio-bluetooth#12]
I was getting the following error on boot before the crypt device password prompt:

```
Bluetooth: hci0: Failed to load Intel firmware file intel/ibt-0041-0041.sfi (-2)
```

Turns out the mkinitcpio-bluetooth is not pulling the right modules/files into the initramfs image and I had to manually add the following to my `/etc/mkinitcpio.conf` to fix the issue (without this fix, my bluetooth adapter would not work at all):

```
FILES=(/usr/lib/firmware/intel/ibt-0041-0041.*)
```

and now the error is gone and everything's dandy:

```
Bluetooth: hci0: Firmware timestamp 2022.12 buildtype 1 build 41819
Bluetooth: hci0: Found device firmware: intel/ibt-0041-0041.sfi
Bluetooth: hci0: Boot Address: 0x100800
Bluetooth: hci0: Firmware Version: 91-12.22
Bluetooth: hci0: Firmware already loaded
```

**Comment by irreleph4nt** [comment]
Hi @oxplot and thank you for your feedback! 
This particular problem was mentioned in some of the other issues here on Github, which is why I keep them open as a reference. I had hoped that point 4 of the Setup section in the README made this requirement clear, but looks like I need to improve that wording a bit.

Anyway, cheers!

**Comment by oxplot** [comment]
Ah sorry, I didn't re-check the readme after I installed the package more than a year ago.
