### ISSUE TITLE
What would be required for this to work with systemd-boot?

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [irreleph4nt/mkinitcpio-bluetooth#13]
You mentioned your hook will not work with systemd.

Do you happen to know if it is at all possible to have BT working with systemd-boot?
I am having great difficulties finding resources on how to get my BT keyboard working at boot time.
Need to unlock my luks encrypted disk. 
For which I can use my laptop keyboard of course, but would really like to use my external keyboard instead.

**Comment by irreleph4nt** [comment]
Hi,
The problem is that systemd unit files are started in a particular order. My previous attempts at making that work all failed because systemd would always start bluetooth right _**after**_ the luks password prompt - i.e. after one had to enter the passphrase - which rendered the whole thing useless. What may get you on the right path is to review [this pull request](https://github.com/dracutdevs/dracut/pull/1139) which added bluetooth connectivity to dracut, a competitor of mkinitcpio. Also have a look at [this dicussion](https://github.com/dracutdevs/dracut/pull/544#issuecomment-734248887) which shows how they got around the unit fiile not starting early enough during boot.

**Comment by daftaupe** [comment]
Hello,
I would like to give using systemd a try.
@irreleph4nt do you maybe have some remaining work files in a branch or something about it, so that it would be easier to start ?
