### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by zzzardoz** [irreleph4nt/mkinitcpio-bluetooth#2]
Hi! I can't get this to work on my box. My keyboard (Logitech Craft) was paired via Gnome Settings. And this is my [mkinitcpio.conf](https://pastebin.com/LnNcZsnJ) and [main.conf](https://pastebin.com/QEf8n47W). Am I doing something wrong? Like wrong hook order or do I have to pair via bluetoothctl?

**Comment by irreleph4nt** [comment]
Hi,

Your main.conf looks like the one I use, so that should be fine. Have you followed the instructions given in my README as well as on the Arch Wiki regarding pairing and tursting? I am not using Gnome so I can't test that for you.

A few things remain that you can check:

1. Does your keyboard require any drivers or binaries to work beyond plain bluetooth? If so, you'll have to add them to your mkinitcpio.conf

2. Does Gnome create the required profile data as mentioned in the README? This is important because the hook copies the relevant folders to your initcpio.

3. Have you adjusted the hardware ID as instructed in the README? Otherwise your machine will not find your keyboard to connect to during boot.

4. What's the output regarding bluetooth that you see during boot / before you are prompted for your LUKs password?

5. Have you installed all required bluetooh packages as instructed in the README / on the Arch Wiki?

6. Have you tried pairing and trusting your keyboard via bluetoothctl? As I am not using Gnome, this is the method I used and can confirm to work.

7. The HOOKS array you use differs from mine in order. For reference, this is what I use: HOOKS=(base udev autodetect modconf keyboard keymap bluetooth block encrypt lvm2 filesystems fsck)

**Comment by irreleph4nt** [comment]
Closing due to lack of feedback.
