### ISSUE TITLE
Continues to work after boot?

### ISSUE THREAD

**Issue by jamesrobb** [irreleph4nt/mkinitcpio-bluetooth#3]
Hello,

Not actually an issue, but I wasn't sure how else to ask you this question. Assuming I get this to work so that I have bluetooth keyboard functionality when it's time to enter my decryption passphrase, will the keyboard continue to function seamlessly after the OS has booted and prompts me for my user password?

**Comment by irreleph4nt** [comment]
Hello,

As the hook pulls the already existing bluetooth profile of your keyboard into initramfs instead of creating a new one, I expect it to work just fine after boot as well. I myself have never had issues due to that. It's important however that you pair **_and_** trust your keyboard first from within the OS before you set this hook up.

**Comment by jamesrobb** [comment]
Makes sense.

I'm having some trouble getting this to work at all. I'm able to install the package and run `mikinitcpio` without any problems, and I've followed all the steps you've listed.

Is there any limitations on the type of keyboard (for example an apple bt keyboard), or keyboards that require a pin?

Is there any good way to debug this? Hopefully its just some small error that can be corrected if I could see where it is failing.

**Comment by irreleph4nt** [comment]
I have tested this only with USB dongles, so if for example you are using an integrated BT module of your laptop you probably need to make sure you have all the drivers for it in the initramfs as well. You'd do that by using the other arrays in your mkinitcpio.conf file as normal. To me this sounds like the most probable issue.

When you have installed the hook, reboot. Even if it fails to work you can then access the journal as captured during the boot process as well as dmesg output. These two together usually tell you what's wrong, when you are missing drivers for example.

**Comment by jamesrobb** [comment]
I see, yes, I am using an integrated BT module. However, when I dig through `lsusb`/etc, it seems that the driver/module associated with the internal adaptor is `btusb`. 

I'm not really sure how to see the output before the LUKS password prompt comes up. On my system, I go straight from a Lenovo logo to the password prompt. If some output is there, it clears way too fast for me to have ever seen it.

I'm struggling with figuring out how to get debug output of this. I'm not really sure how to determine by looking at the journalctl logs exactly when a boot/reboot started, and when a password has been entered into the LUKS prompt. Is there a "simple" way to determine this or put some strings inside the debug information so that they can be easily searched for? I've found references to the bluetooth modules being started, but I'm not exactly sure when in the process that happens, nor if something went wrong along the way.

Does all the debug output really get written into the dmesg buffer and journalctl? I've read other places about initramfs being its own little kernel. Does that mean not all of its output is available from my OS once its booted?

As for the modules themselves, I edited `bluetooth_install` on line 34 to include every module that seems to be loaded (after the full boot process and I'm at the desktop) that has as "bt" or "bluetooth" in the name. Wouldn't this preclude the need to modify the other arrays you mentioned in `mikinitcpio.conf`?

Lastly , I'm using Manjaro, not Arch. It could be the case that the files/configs added in the hooks are not exactly the same. I'm hoping that getting some good debug info would highlight if that is the case (and how I might fix it).

Thanks :)

**Comment by irreleph4nt** [comment]
One important point that just came to mind reading your feedback: Do you use the systemd hook?
What you write makes me wonder whether your LUKS PW prompt looks something like on this picture:

[Picture found via Google](https://images.app.goo.gl/KFyB7zHeTQBgQdLe6)

If it does then you might be using the systemd or sd-encrypt hooks or something else that triggers systemd-cryptsetup during boot, which be causing your issues.

To get more output during or after boot, here are a few things that come to mind:

1. remove the "quiet" option from your kernel parameters to see text output
2. disable / uninstall splash screen tools like plymouth which hide text from you
3. After boot use:
3a. dmesg | grep Bluetooth
3b. journalctl -b

Journalctl will limit output to the current boot, which will help spotting things.

Generally speaking this hook does *not* work with anything systemd (like hooks) in your boot config. I have tried implementing this functionality for systemd, but no matter what you do and how you set stuff up, bluetooth is always called right *after* disk decryption, which makes it useless.

I am a bit swamped with college work right now, so testing things on a PC myself will have to wait. Sorry.

**Comment by jamesrobb** [comment]
My decrypt screen looks similar, but not quite the same. I do get a message saying that grub has loaded, and then I'm prompted for the password. If I enter the password incorrectly, then the grub rescue console is displayed.

I'm not quite sure if I am using the "wrong" hooks. These are the hooks I had setup.

HOOKS="base udev autodetect modconf block keyboard bluetooth keymap encrypt filesystems fsck"

Figure any of this loads some problem systemd related stuff?

I'll see what I can find out with the debugging advice you given. Thanks.

**Comment by irreleph4nt** [comment]
I can't say whether it will make any difference, but here are the hooks I use for reference:

HOOKS="base udev autodetect modconf keyboard keymap bluetooth block encrypt lvm2 filesystems fsck"

There are some minor difference compared to yours:
- "keyboard, keymap, bluetooth" in that sequence **before** block **and** encrypt
- lvm2 as I have LVM volumes configured on top my encrypted disk. Whether you need this depends on your own system setup

**Comment by jamesrobb** [comment]
I don't see what is depicted in the image you've linked. Is there maybe some flag I can change in my mkinitcpio.conf file to see this information?

I've taken a picture of what I see when I boot up my laptop. First I see the lenovo logo, and then I immediately see what is displayed in the picture. No other text is displayed along the way (that I can see).

[https://i.ibb.co/qgcrynj/IMG-20200321-172723.jpg](https://i.ibb.co/qgcrynj/IMG-20200321-172723.jpg)

**Comment by irreleph4nt** [comment]
Okay, so I think I have figured out what's the issue here, albeit it is not really good news.

I am assuming that you have installed Manjaro using their own setup program. If that is true and you opted to encrypt the system using said installer, then according to the following [source](https://forum.manjaro.org/t/full-system-encryption-without-encrypted-boot/113445) you have encrypted not only your root partition but /boot as well.
It appears that GRUB is not loading any additional modules (or at least I was unable to find sources that say otherwise) when it prompts you for a passphrase, as your kernel is loaded only after that prompt, which is indicated by your bootloader menu showing up after entering your pass.

Now, how do you get wirless keyboard support added to all that? Two options I see that both aren't satisfying:
1. You could change your system layout, which would involve setting up Manjaro again from scratch, this time without using the included installer or looking at the link I posted above when using the installer. The goal would be to encrypt your root partition but leave /boot unencrypted. This way my hook would work as normal.
2. Get a wirless keyboard that does not depend on Bluetooth. Examples are Logitech keyboards that come with a little USB dongle. These work just like keyboards with a cord ... Logitech calls that technology "Unifying" IIRC.

That said, I'd like to close this issue as the issue at hand has nothing to do with this hook per se. I am sorry I can't help you to get this working as I myself use neither Manjaro nor GRUB.

**Comment by jamesrobb** [comment]
This all makes complete sense to me - seems to describe the situation quite accurately.

I agree, this here no reason to keep this open as its not a problem with your hook.

If you'd be willing, could you describe your setup before closing the issue? What does your boot process look like if you aren't using GRUB? It'd be good to know your boot steps so that someone else (or myself) trying to use this has an idea of the environment/setup this hook works in.

**Comment by irreleph4nt** [comment]
I added notes to the README based on our conversation here. Closing.
