### ISSUE TITLE
Why not systemd-compatible?

### ISSUE THREAD

**Issue by leophys** [irreleph4nt/mkinitcpio-bluetooth#7]
Hi, thanks for this hook!
I was wondering what is the reason behind the incompatibility with the `systemd` hook. I'd like very much to use this hook (encrypted root, bluetooth keyboard) but I am puzzled by the first [prerequisite](https://github.com/irreleph4nt/mkinitcpio-bluetooth/blob/master/README.md#prerquisites).

I'd like to contribute to make it compatible.

**Comment by leophys** [comment]
I suspect that the warning at the end of [this section](https://wiki.archlinux.org/index.php/mkinitcpio#Runtime_hooks) explains why.
```
Note: Runtime hooks are only used by busybox init. systemd hook triggers a systemd based init, which does not run any runtime hooks but uses systemd units instead.
```

**Comment by irreleph4nt** [comment]
Hi and thank you for your feedback. The problem is related to what you found but not per se a matter of hook vs no hook. Systemd, as the text tells you, uses units just like the service files you already have. The problem is the scheduling of those units. Whilst trying it out I found no way of forcing systemd to load the bluetooth unit *before* the encryption unit, which renders this useless. I am happy to accept pull requests if you want to spend time on making this work. We could have a simple check to see if a user uses systemd or not to enable the right version of this hook for them.
